# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "lazyman"
  s.version = "0.1.13"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Franko"]
  s.date = "2013-10-31"
  s.description = "A test framework using watir-webdriver rspec and page-object"
  s.email = "dan.franko@yale.edu"
  s.executables = ["lazyman"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/lazyman",
    "lazyman.gemspec",
    "lib/lazyman.rb",
    "lib/lazyman/cli.rb",
    "lib/lazyman/errors.rb",
    "lib/lazyman/ext/string.rb",
    "lib/lazyman/generators/lazyman/.rspec",
    "lib/lazyman/generators/lazyman/app/spec/yale/yale_example_spec.rb",
    "lib/lazyman/generators/lazyman/app/spec/shared/login.rb",
    "lib/lazyman/generators/lazyman/app/spec/spec_helper.rb.tt",
    
    "lib/lazyman/generators/lazyman/app/spec/support/formatters/dry_run_formatter.rb",
    "lib/lazyman/generators/lazyman/app/spec/support/formatters/html_override.rb",
    "lib/lazyman/generators/lazyman/app/spec/support/formatters/lazyman_formatter.rb",
    
    "lib/lazyman/generators/lazyman/app/spec/support/matchers/custom_matcher.rb",
    "lib/lazyman/generators/lazyman/app/spec/support/matchers/email_matcher.rb",
    "lib/lazyman/generators/lazyman/app/spec/support/matchers/file_matcher.rb",
    
    "lib/lazyman/generators/lazyman/app/matchers/.empty_directory",
    "lib/lazyman/generators/lazyman/app/pages/%name%_navigator.rb.tt",
    "lib/lazyman/generators/lazyman/app/pages/%name%_page.rb.tt",
    "lib/lazyman/generators/lazyman/app/pages/yale/yale_page.rb.tt",
    "lib/lazyman/generators/lazyman/app/pages/yale/yale_search_result_page.rb.tt",
    "lib/lazyman/generators/lazyman/app/reports/.empty_directory",
    "lib/lazyman/generators/lazyman/app/reports/screenshots/.empty_directory",
    "lib/lazyman/generators/lazyman/app/test_data/baidu.yml",
    "lib/lazyman/generators/lazyman/app/test_data/login_user.yml",
    "lib/lazyman/generators/lazyman/bin/console",
    "lib/lazyman/generators/lazyman/bin/console.bat",
    "lib/lazyman/generators/lazyman/bin/setup.rb.tt",
    "lib/lazyman/generators/lazyman/config/config.yml",
    "lib/lazyman/generators/lazyman/config/lazyman_formatter.rb",
    "lib/lazyman/generators/lazyman/config/override.rb",
    "lib/lazyman/templates/browser_spec_template.rb.tt",
    "lib/lazyman/templates/web_service_template.rb.tt",
    "lib/lazyman/templates/plain_template.rb.tt",
    "lib/lazyman/templates/template_page.rb.tt",
    "lib/lazyman/lazy_config.rb",
    "lib/lazyman/lazy_initializer.rb",
    "lib/lazyman/lazy_navigator.rb",
    "lib/lazyman/lazy_page.rb",
    "spec/app/pages/components/footer.rb",
    "spec/app/pages/components/sub/sub_footer.rb",
    "spec/app/pages/module1/module1_page.rb",
    "spec/app/pages/module1/sub_test_page.rb",
    "spec/app/pages/test_navigator.rb",
    "spec/app/pages/test_page.rb",
    "spec/config/config.yml",
    "spec/config/wrong_config.yml",
    "spec/lazy_config_spec.rb",
    "spec/lazy_initializer_spec.rb",
    "spec/lazy_navigator_spec.rb",
    "spec/lazy_page_spec.rb",
    "spec/pages/components/footer.rb",
    "spec/pages/test_page.rb",
    "spec/spec_helper.rb",
    "spec/string_spec.rb"
  ]
  s.homepage = "https://github.com/dmfranko/lazyman"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "A simple web automation test framework"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, [">= 2.13.0"])
      s.add_runtime_dependency(%q<page-object>, [">= 0.8.6.1"])
      s.add_runtime_dependency(%q<thor>, [">= 0.14.6"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<page-object>, [">= 0.8.6.1"])
      s.add_development_dependency(%q<thor>, [">= 0.14.6"])
    else
      s.add_dependency(%q<rspec>, [">= 2.13.0"])
      s.add_dependency(%q<page-object>, [">= 0.8.6.1"])
      s.add_dependency(%q<thor>, [">= 0.14.6"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rspec>, [">= 2.13.0"])
      s.add_dependency(%q<page-object>, [">= 0.8.6.1"])
      s.add_dependency(%q<thor>, [">= 0.14.6"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.13.0"])
    s.add_dependency(%q<page-object>, [">= 0.8.6.1"])
    s.add_dependency(%q<thor>, [">= 0.14.6"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rspec>, [">= 2.13.0"])
    s.add_dependency(%q<page-object>, [">= 0.8.6.1"])
    s.add_dependency(%q<thor>, [">= 0.14.6"])
  end
end

