# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "magicspec"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["dmfranko"]
  s.date = "2014-02-18"
  s.description = "A test framework using watir-webdriver rspec and page-object"
  s.email = "dan.franko@yale.edu"
  s.executables = ["magicspec"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".project",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "bin/magicspec",
    "magicspec.gemspec",
    "lib/magicspec.rb",
    "lib/magicspec/cli.rb",
    "lib/magicspec/errors.rb",
    "lib/magicspec/ext/string.rb",
    "lib/magicspec/generators/magicspec/.rspec",
    "lib/magicspec/generators/magicspec/app/matchers/.empty_directory",
    "lib/magicspec/generators/magicspec/app/pages/yale/yale_page.rb.tt",
    "lib/magicspec/generators/magicspec/app/pages/yale/yale_search_result_page.rb.tt",
    "lib/magicspec/generators/magicspec/app/reports/.empty_directory",
    "lib/magicspec/generators/magicspec/app/reports/screenshots/.empty_directory",
    "lib/magicspec/generators/magicspec/app/spec/shared/login.rb",
    "lib/magicspec/generators/magicspec/app/spec/spec_helper.rb.tt",
    "lib/magicspec/generators/magicspec/app/spec/support/formatters/dry_run_formatter.rb",
    "lib/magicspec/generators/magicspec/app/spec/support/formatters/html_override.rb",
    "lib/magicspec/generators/magicspec/app/spec/support/formatters/magicspec_formatter.rb",
    "lib/magicspec/generators/magicspec/app/spec/support/matchers/custom_matcher.rb",
    "lib/magicspec/generators/magicspec/app/spec/support/matchers/email_matcher.rb",
    "lib/magicspec/generators/magicspec/app/spec/support/matchers/file_matcher.rb",
    "lib/magicspec/generators/magicspec/app/spec/yale/yale_example_spec.rb",
    "lib/magicspec/generators/magicspec/app/test_data/baidu.yml",
    "lib/magicspec/generators/magicspec/app/test_data/login_user.yml",
    "lib/magicspec/generators/magicspec/bin/console",
    "lib/magicspec/generators/magicspec/bin/console.bat",
    "lib/magicspec/generators/magicspec/bin/setup.rb.tt",
    "lib/magicspec/generators/magicspec/config/config.yml",
    "lib/magicspec/generators/magicspec/config/magicspec_formatter.rb",
    "lib/magicspec/generators/magicspec/config/override.rb",
    "lib/magicspec/magicspec_config.rb",
    "lib/magicspec/magicspec_initializer.rb",
    "lib/magicspec/page_override.rb",
    "lib/magicspec/templates/browser_spec_template.rb.tt",
    "lib/magicspec/templates/mobile_template.rb.tt",
    "lib/magicspec/templates/plain_template.rb.tt",
    "lib/magicspec/templates/template_page.rb.tt",
    "lib/magicspec/templates/web_service_template.rb.tt",
    "spec/app/pages/components/footer.rb",
    "spec/app/pages/components/sub/sub_footer.rb",
    "spec/app/pages/module1/module1_page.rb",
    "spec/app/pages/module1/sub_test_page.rb",
    "spec/app/pages/test_navigator.rb",
    "spec/app/pages/test_page.rb",
    "spec/config/config.yml",
    "spec/config/wrong_config.yml",
    "spec/magicspec_config_spec.rb",
    "spec/lazy_initializer_spec.rb",
    "spec/lazy_navigator_spec.rb",
    "spec/lazy_page_spec.rb",
    "spec/pages/components/footer.rb",
    "spec/pages/test_page.rb",
    "spec/spec_helper.rb",
    "spec/string_spec.rb"
  ]
  s.homepage = "https://github.com/dmfranko/magic_spec"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "A simple web automation test framework"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<page-object>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<fuubar>, [">= 0"])
      s.add_runtime_dependency(%q<rspec-rerun>, [">= 0"])
      s.add_runtime_dependency(%q<watir-webdriver>, [">= 0"])
      s.add_runtime_dependency(%q<watir-browser-factory>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<page-object>, [">= 0"])
      s.add_development_dependency(%q<thor>, [">= 0"])
    else
      s.add_dependency(%q<page-object>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<page-object>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
    end
  else
    s.add_dependency(%q<page-object>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<page-object>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
  end
end

